### ISSUE TITLE
Installing the dependencies

### ISSUE THREAD

**Issue by PaulBonnot** [xldenis/whycode#16]
How do I install the dependencies ?
Using `opam install . --deps-only` gives me an error because of conflicting packages.
If I try to install the dependencies by hand I get versions with a different API than the ones that seems to be used by the code.
For instance I can't find a version on the package `jsonrpc` that has a `Notification` module and which does not conflict with `linol-lwt`.

**Comment by xldenis** [comment]
There are required pins which unfortunately opam lock files are insufficient to properly... pin

**Comment by PaulBonnot** [comment]
Oh it was the `--locked` argument that was missing, thanks.
