### ISSUE TITLE
Support for MacOS

### ISSUE THREAD

**Issue by mojeanmac** [xldenis/whycode#17]
`DEBUG_SERVER_PATH` is currently hardcoded as an `.exe` in `launch.json`

**Comment by xldenis** [comment]
> DEBUG_SERVER_PATH is currently hardcoded as an .exe in launch.json

Despite being an `.exe`, it works on Mac, that's just what `dune` suffixes its executables with.

**Comment by mojeanmac** [comment]
Interesting! Dune was failing to create `main.exe` due to errors in `main.ml`, specifically pertaining to the use of `server` on lines 4 and 6:
```
This expression has type env:unit -> Linol_lwt.Jsonrpc2.t
but an expression was expected of type Linol_lwt.Jsonrpc2.t
Hint: Did you forget to provide `()' as argument?
```
So I changed line 3 to say:
```ocaml
let server = (Linol_lwt.Jsonrpc2.create_stdio s) () in
```
However I'm not sure if this was the optiaml fix since now I get a warn that `label env was omitted in the application of this function`...

**Comment by xldenis** [comment]
Hmm, its possible you aren't using the same version of linol as me, I have it pinned to my fork: `github.com/xldenis/linol`.

**Comment by mojeanmac** [comment]
Closing since Mac support was there all along (lol), and so far `cargo creusot` + `why3find prove` has been adequate for developing my Rust proofs fairly quickly.
