### ISSUE TITLE
pin-depends in `whycode.opam`

### ISSUE THREAD

**Issue by Lysxia** [xldenis/whycode#19]
The pin-depends pins why3 to a remote repository. But what if I want to pin it to a local version on my machine? Is there an opam flag for that or should we remove pin-depends from `whycode.opam`?

**Comment by xldenis** [comment]
> The pin-depends pins why3 to a remote repository. But what if I want to pin it to a local version on my machine? Is there an opam flag for that or should we remove pin-depends from whycode.opam?

I think you can just override the in in opam. I would like to keep things locked because otherwise having reproducible builds with ocaml is near impossible.

**Comment by Lysxia** [comment]
Okay I understand and I can work with that. The opam doc says it's supposed to prompt about the `pin-depends` so the overwriting behavior I saw might have been because of an overeager `-y` flag.
